###
POST https://dummyjson.com/products/add
Content-Type: application/json

{
  "name": "Pumpkin",
  "price": 1.99,
  "description": "A pumpkin",
  "thumbnail": "https://dummyimage.com/400x400/000/fff&text=pumpkin"
}

###
http://localhost:3000

###
POST http://localhost:3000/api/v1/products/seed

###
http://localhost:3000/api/v1/products

###
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "title": "Pumpkin",
  "price": 1.99,
}

###
PATCH http://localhost:3000/api/v1/products/31
Content-Type: application/json

{
  "title": "Pumpkin Spice Latte",
  "price": 2.99,
}

###
https://jackgusler-cps493-class-webservice.onrender.com/api/v1/products/28